import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Demo() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Frontend Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.grid}>
         
            <p>Find in-depth data API.</p>
            <p>ملاحظات ايجاد مسار المعلومات</p>
          

          
        </div>
      </main>

      <footer className={styles.footer}>
       Myfooter
      </footer>
    </div>
  )
}
